import Foundation

// MARK: - DocumentEmbedding

/// A single document's pre-computed embedding vector from the bundle.
///
/// Generated by the CLI tool (`ssk embed`) and loaded at runtime by
/// ``EmbeddingStorage``.
///
/// The JSON stores floating-point values as `Double`; this type
/// down-casts to `Float` on decode to halve the in-memory footprint.
public struct DocumentEmbedding: Sendable, Codable {

    /// Unique identifier matching the document's ``SemanticSearchable/searchID``.
    public let id: String

    /// L2-normalised embedding vector (e.g. 384 dimensions for E5-small).
    public let embedding: [Float]

    public init(id: String, embedding: [Float]) {
        self.id = id
        self.embedding = embedding
    }
}

// MARK: - Codable (Double -> Float)

extension DocumentEmbedding {

    private enum CodingKeys: String, CodingKey {
        case id
        case embedding
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        // JSON encodes as [Double]; down-cast to [Float] to halve memory usage.
        let doubles = try container.decode([Double].self, forKey: .embedding)
        embedding = doubles.map(Float.init)
    }
}
