import Foundation
import os.log

// MARK: - EmbeddingStorage

/// Loads and caches pre-computed document embeddings from the app bundle.
///
/// The embedding index file (`embeddings_index.json` by default) is
/// generated by the CLI tool (`ssk embed`) and should be added to your
/// app's bundle resources.
///
/// ## Usage
///
/// In most cases, use the ``shared`` singleton which reads its
/// configuration from ``SemanticSearchKit/configure(modelName:bundle:queryPrefix:dimension:maxSeqLen:)``:
///
/// ```swift
/// let embeddings = try await EmbeddingStorage.shared.loadAll()
/// ```
///
/// For custom setups, create an instance directly:
///
/// ```swift
/// let storage = EmbeddingStorage(fileName: "my_embeddings", bundle: .module)
/// ```
public actor EmbeddingStorage: EmbeddingProviding {

    // MARK: - Shared instance

    /// Shared singleton configured via ``SemanticSearchKit/configure(modelName:bundle:queryPrefix:dimension:maxSeqLen:)``.
    public static let shared = EmbeddingStorage()

    // MARK: - Properties

    private let fileName: String
    private let bundle: Bundle
    private var cache: [String: [Float]]?

    private static let logger = Logger(
        subsystem: "com.semanticsearchkit",
        category: "EmbeddingStorage"
    )

    // MARK: - Initialisation

    /// Creates an embedding storage reading from the specified bundle resource.
    ///
    /// - Parameters:
    ///   - fileName: Base name of the JSON file (without extension). Default: `"embeddings_index"`.
    ///   - bundle: The bundle containing the file. Default: `.main`.
    public init(
        fileName: String? = nil,
        bundle: Bundle? = nil
    ) {
        self.fileName = fileName ?? Configuration.shared.embeddingsFileName
        self.bundle = bundle ?? Configuration.shared.bundle
    }

    // MARK: - EmbeddingProviding

    /// Returns all embeddings as a dictionary keyed by document ID.
    ///
    /// The first call loads from the bundle; subsequent calls return
    /// the in-memory cache.
    public func loadAll() throws -> [String: [Float]] {
        if let cache { return cache }

        let records = try loadFromBundle()
        var dict = [String: [Float]](minimumCapacity: records.count)
        for record in records {
            dict[record.id] = record.embedding
        }
        cache = dict
        Self.logger.debug("Loaded \(records.count) embeddings from bundle")
        return dict
    }

    /// Returns the embedding for a single document ID, or `nil` if not found.
    public func embedding(for documentID: String) throws -> [Float]? {
        try loadAll()[documentID]
    }

    // MARK: - Private

    private func loadFromBundle() throws -> [DocumentEmbedding] {
        guard let url = bundle.url(forResource: fileName, withExtension: "json") else {
            throw EmbeddingStorageError.fileNotFoundInBundle(fileName: fileName)
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode([DocumentEmbedding].self, from: data)
    }
}

// MARK: - Errors

/// Errors thrown by ``EmbeddingStorage``.
public enum EmbeddingStorageError: Error, LocalizedError, Sendable {
    /// The embedding index file was not found in the bundle.
    case fileNotFoundInBundle(fileName: String)

    public var errorDescription: String? {
        switch self {
        case .fileNotFoundInBundle(let name):
            return "\(name).json not found in app bundle. "
                + "Generate it with `ssk embed` and add it to your Xcode target's resources."
        }
    }
}
